---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pm25-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pm25
    spec:
      containers:
      - name: pm25
        image: childzu/myrepo:pm25
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pm25-svc
  labels:
    app: pm25
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 8080
  selector:
    app: pm25
